# Generated by Django 2.2.3 on 2020-03-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_liuyan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liuyan',
        ),
    ]
